### PR TITLE
getting-started branch

### PR DESCRIPTION
**Pull request by burntyellow**
Added a Getting Started section to manual.

### CODE REVIEW

**Review by Comeani — APPROVED** [review]
This looks good, I fixed a few warnings that were showing up when I served the content locally. 

The only think we might want to loop back around on that I could find was that when you go to the terminal/ondemand/jupyterhub links from the getting started section, it jumps the nav over to the other section in the side bar which could be slightly confusing. Overall not a huge problem to deal with though.

**Comment by Comeani** [comment]
@burntyellow Is your navigation functionality dependent on the overview pages under the different getting started sections being called `index.html`?

**Comment by burntyellow** [comment]
> @burntyellow Is your navigation functionality dependent on the overview pages under the different getting started sections being called `index.html`?

Yes. This is described in the Section index pages of https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#hiding-the-sidebars-hide-table-of-contents

**Comment by burntyellow** [comment]
@Comeani Can you double check the getting_started branch locally and merge if all good?

**Pull request merged**
