### PR TITLE
Update vscode.md

### PR DESCRIPTION
**Pull request by fanurs**
Hi, I just set up my VS Code on my Windows machine according to the instructions, and I would like to propose:
- Removed backslash. Was this intended? It didn't work with blackslash for my case.
- Appending instead of overwriting the `id_rsa`

### CODE REVIEW

**Comment by fangpingmu** [comment]
"Appending instead of overwriting the id_rsa" This is correct. Where do you find the "overwriting the id_rsa" statement?

**Comment by fanurs** [comment]
Sorry, I meant to say it overwrites `authorized_keys`:
https://github.com/pitt-crc/user-manual/blob/3cc15902406bd4d5028eb47a7f02377cdd1cf12a/docs/slurm/vscode.md?plain=1#L63

I propose doing `cat id_rsa.pub >> authorized_keys` instead.

**Comment by fangpingmu** [comment]
Thanks to report this problem. I have changed https://crc-pages.pitt.edu/user-manual/slurm/vscode/

**Comment by chnixi** [comment]
Windows does not support the ControlMaster functionality, and the syntax convention for backslash and double quotes is different than On Linux/Mac. The current VSCode user manual page needs to be modified and confirmed (already partially done).

**Pull request merged**
